### ISSUE TITLE
Memory managment

### ISSUE THREAD

**Issue by mario-bucev** [LPD-EPFL/CS453-2019-project#4]
Hi (yes, it's me again :) ),
In the section "Evaluation machine" of the readme, it says that we can consider RAM "unlimited."
Is it then ok to leak some memory or delay its reclamation? For instance, would it be acceptable to not reclaim any unused memory during the lifetime of a `shared_t` and only do that on `tm_destroy`?

Thank you.

**Comment by srlt** [comment]
Exactly. "RAM unlimited" means you can postpone memory reclamation as much as you want,
as long as it is all properly freed after `tm_destroy` (otherwise the specification is not followed, and the implementation is technically-speaking incorrect).

Just be careful about one fact: the `grading` tool limits the time spent in `tm_destroy` (see https://github.com/LPD-EPFL/CS453-2019-project/blob/master/grading/transactional.hpp#L185).
One student last year had a problem with many `free`s taking too long to run.

**Comment by mario-bucev** [comment]
Great, thank you for the quick response
